# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=imd.models.upload_images_to)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imd.Category')),
            ],
        ),
    ]
