# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='galley/')),
                ('thumbnail', models.ImageField(upload_to='gallery/thumbnail/')),
                ('desc', models.TextField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imd.Category')),
            ],
        ),
    ]
